### ISSUE TITLE
how to get the location of the spikes in a common coordinate space

### ISSUE THREAD

**Issue by adezfouli** [nsteinme/steinmetz-et-al-2019#1]
My question is how to get the location of spikes in a common coordinate space. 

Would that be enough to get the cluster of the spike (from `spikes.clusters`),  and then getting the peakChannel from `clusters.peakChannel` and finally getting `channels.brainLocation.tsv`?

**Comment by nsteinme** [comment]
Yes, that is correct. Sorry, I can see that this seems like an extra step and it would have been helpful to include a `clusters.brainLocation` directly, but in any case you got it right.

**Comment by adezfouli** [comment]
@nsteinme  Another related question about how to match `clusters.peakChannel`  to `channels.brainLocation.tsv`. The indices in `clusters.peakChannel` start from 1 (not zero). Does it mean that the channel number 1 matches the first row of `channels.brainLocation.tsv`?

**Comment by guidomeijer** [comment]
I see this was a long time ago but I have the same question

**Comment by nsteinme** [comment]
Sorry to have missed answering this earlier. Yes, clusters.peakChannel ->
channels.brainLocation. I believe it will be 1-indexed (made all this in
matlab...).

Nick
