### ISSUE TITLE
Broken ALF link in wiki

### ISSUE THREAD

**Issue by rossant** [nsteinme/steinmetz-et-al-2019#5]
Issue found by Angus Campbell:

On [this page](https://github.com/nsteinme/steinmetz-et-al-2019/wiki/data-files), the link in the "File naming" section, in the sentence "Files are named using the "ALF" naming convention, which you can read about in detail here." is broken, here is the correct one: https://int-brain-lab.github.io/iblenv/one_docs/one_reference.html#alf

**Comment by nsteinme** [comment]
thanks Cyrille and Angus - fixed
